"""The schema Alembic sees is the whole schema, and the migrations build exactly it.

`migrations/env.py` compares the migrations against `app.models_all.metadata`. A table whose
module the registry forgot is one `alembic check` proposes to drop, and one the next
autogenerated migration would be written without: `emergency_card`, `notice`,
`what_to_do_card` and `review_item` were all missing that way.

Both checks run in a fresh interpreter. This test process has already imported every model
(and a few test-only tables) through the fixtures, which would hide a missing import.
"""

from __future__ import annotations

import ast
import os
import subprocess
import sys
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
APP = BACKEND / "app"


def _names_a_table(statement: ast.stmt) -> bool:
    if isinstance(statement, ast.Assign):
        return any(isinstance(t, ast.Name) and t.id == "__tablename__" for t in statement.targets)
    if isinstance(statement, ast.AnnAssign):
        return isinstance(statement.target, ast.Name) and statement.target.id == "__tablename__"
    return False


def _table_modules() -> set[str]:
    """Every module under app/ that declares a class with a `__tablename__`, read from the
    source rather than imported, so nothing has to be loaded to be found."""
    found = set()
    for path in APP.rglob("*.py"):
        for node in ast.parse(path.read_text()).body:
            if isinstance(node, ast.ClassDef) and any(_names_a_table(s) for s in node.body):
                found.add(".".join(path.relative_to(BACKEND).with_suffix("").parts))
    return found


def _run(*argv: str, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, *argv], cwd=BACKEND, env=env, capture_output=True, text=True, check=False
    )


def test_the_registry_loads_every_module_that_declares_a_table() -> None:
    declared = _table_modules()
    assert len(declared) > 20, declared
    loaded = _run(
        "-c",
        "import sys, app.models_all; print('\\n'.join(m for m in sys.modules if m.startswith('app.')))",
    )
    assert loaded.returncode == 0, loaded.stderr
    missing = declared - set(loaded.stdout.split())
    assert missing == set(), f"add these to app/models_all.py: {sorted(missing)}"


def test_the_migrations_build_exactly_the_models(tmp_path: Path) -> None:
    """`alembic upgrade heads` then `alembic check` on an empty database: any difference
    between what the migrations build and what the models declare fails here."""
    env = {k: v for k, v in os.environ.items() if not k.startswith("NURA_")}
    env |= {"NURA_REGION": "SG", "NURA_DATABASE_URL": f"sqlite+aiosqlite:///{tmp_path / 'c.db'}"}
    upgraded = _run("-m", "alembic", "upgrade", "heads", env=env)
    assert upgraded.returncode == 0, upgraded.stderr
    checked = _run("-m", "alembic", "check", env=env)
    assert checked.returncode == 0, checked.stdout + checked.stderr
